export const PLANS = {
  free: {
    id: 'free',
    name: 'Free',
    price: 0,
    period: '',
    description: 'Limited access to get started.',
    featured: false,
    features: [
      'Up to 3 patients',
      'Basic patient profiles',
      'Session scheduling',
      'Email support',
    ],
    modules: {
      dashboard: 'available',
      patients: { status: 'available', max: 3 },
      alerts: { status: 'available', max: 5 },
      reports: 'locked',
      statistics: 'locked',
      settings: 'available',
      administration: 'locked',
      advancedMonitoring: 'locked',
      apiAccess: 'locked',
    },
    limits: {
      patients: 3,
      caregivers: 1,
      alertsPerDay: 5,
    },
  },
  basic: {
    id: 'basic',
    name: 'Basic',
    price: 29,
    period: '/month',
    description: 'Essential tools for small clinics starting with dialysis patient management.',
    featured: false,
    features: [
      'Up to 20 patients',
      'Basic patient profiles',
      'Session scheduling',
      'Email notifications',
      'Standard reports',
      'Email support',
    ],
    modules: {
      dashboard: 'available',
      patients: { status: 'available', max: 20 },
      alerts: { status: 'available', max: 50 },
      reports: 'available',
      statistics: 'locked',
      settings: 'available',
      administration: 'locked',
      advancedMonitoring: 'locked',
      apiAccess: 'locked',
    },
    limits: {
      patients: 20,
      caregivers: 2,
      alertsPerDay: 50,
    },
  },
  professional: {
    id: 'professional',
    name: 'Professional',
    price: 79,
    period: '/month',
    description: 'Complete solution for growing practices with advanced monitoring needs.',
    featured: true,
    features: [
      'Up to 100 patients',
      'Advanced patient profiles',
      'Real-time vital monitoring',
      'Multi-channel alerts',
      'Analytics & reports',
      'Priority support',
      'Team collaboration',
      'API access',
    ],
    modules: {
      dashboard: 'available',
      patients: { status: 'available', max: 100 },
      alerts: 'available',
      reports: 'available',
      statistics: 'available',
      settings: 'available',
      administration: 'available',
      advancedMonitoring: 'available',
      apiAccess: 'available',
    },
    limits: {
      patients: 100,
      caregivers: 5,
      alertsPerDay: -1,
    },
  },
  enterprise: {
    id: 'enterprise',
    name: 'Enterprise',
    price: 199,
    period: '/month',
    description: 'Full-scale platform for hospitals and large dialysis networks.',
    featured: false,
    features: [
      'Unlimited patients',
      'Custom patient fields',
      'Advanced monitoring suite',
      'Critical alert system',
      'Custom reports & BI',
      'Dedicated support manager',
      'White-label options',
      'SSO & SAML',
      'On-premise deployment',
      'SLA guarantee',
    ],
    modules: {
      dashboard: 'available',
      patients: { status: 'available', max: -1 },
      alerts: 'available',
      reports: 'available',
      statistics: 'available',
      settings: 'available',
      administration: 'available',
      advancedMonitoring: 'available',
      apiAccess: 'available',
    },
    limits: {
      patients: -1,
      caregivers: -1,
      alertsPerDay: -1,
    },
  },
};

export const ROLES = {
  patient: {
    label: 'Patient',
    modules: ['dashboard', 'patients', 'alerts'],
    restrictedFrom: ['settings', 'administration', 'users'],
  },
  caregiver: {
    label: 'Caregiver',
    modules: ['dashboard', 'patients', 'alerts', 'reports', 'settings', 'administration', 'users'],
    restrictedFrom: [],
  },
  admin: {
    label: 'Administrator',
    modules: ['dashboard', 'patients', 'alerts', 'reports', 'statistics', 'settings', 'administration', 'users'],
    restrictedFrom: [],
  },
};

export const MODULE_LABELS = {
  dashboard: 'Dashboard',
  patients: 'Patients',
  alerts: 'Alerts',
  reports: 'Reports',
  statistics: 'Statistics',
  settings: 'Settings',
  administration: 'User Management',
  advancedMonitoring: 'Advanced Monitoring',
  apiAccess: 'API Access',
};
